config/routes.rb
Rails.application.routes.draw do
  resources :lessons

  resources :classrooms

  root 'lessons#index'

  get 'classroom/available' => 'classrooms#available'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	has_many :lessons
	validates :name, presence: true
	validate :occupancy_not_negative

	def occupancy_not_negative
		if max_occupancy == nil || max_occupancy < 1
			errors.add(:max_occupancy, "must be a positive value")
		end
	end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    #determine ordering of classrooms
    sort = params[:sort] || session[:sort]
    case sort
    when 'name'
      ordering = :name
    when 'occupancy'
      ordering = 'max_occupancy DESC'
    end

    if params[:sort] != session[:sort]
      session[:sort] = sort
    end
    @classrooms = Classroom.all.order(ordering)
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  #def edit
  #end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end


    def classNotOccupiedAtTime(classroom, date, start, finish)
      #build of off classNotOccupiedOnDay
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:name, :max_occupancy, :details, :color)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
	def get_available_classrooms(day,start,finish)
		classrooms = Classroom.all
		available_classrooms = classrooms.where()
	end
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div>
    <%= f.label :name %>
    </div>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <div>
    <%= f.label :max_occupancy %>
    </div>
    <%= f.number_field :max_occupancy %>
  </div>
  <div class="field">
    <div>
    <%= f.label :color %>
    </div>
    <%= f.select :color, ["Olive", "Green", "Yellow", "Red", "Orange", "DarkRed", "Violet", "Brown", "Maroon", "Blue", "Navy", "Gray"] %>
  </div>

  <div class="field">
    <div>
    <%= f.label :details %>
    </div>
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/available.html.erb
<h1>Available Classrooms</h1>
<%= link_to "Back", new_lesson_path %>

<%= form_tag classroom_available_path, :method => :get, :id => 'times_form' do %>
  <%= hidden_field_tag "title_sort", true if @title_header %>
  View Classrooms:<br>
  &nbsp From: <%= time_select(:starts_at, :get, selected: @start_time, :ignore_date => true, prompt: true, ampm: true) %> <br>
  &nbsp &nbsp &nbsp To: <%= time_select(:ends_at, :get, selected: @end_time, :ignore_date => true, prompt: true, ampm: true) %> <br>
  &nbsp On: <%= date_select(:day, :get, selected: @date) %> <br>

  <%= submit_tag 'Refresh', :id => 'times_submit' %>
<% end %>

<table id="classrooms_available">
  <thead>
    <tr>
      <th id="name_header"><%=link_to 'Name', classroom_available_path(:sort => 'name')%></th>
      <th id="occupancy_header"><%=link_to 'Max occupancy', classroom_available_path(:sort => 'occupancy')%></th>  
      <th>Details</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @available_classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.name %></td>
        <td><%= classroom.max_occupancy %></td>
        <td><%= classroom.details %></td>
        <td><%= link_to 'Select', new_lesson_path(:location => classroom.name) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
&nbsp<%= "No Available Classrooms" if @available_classrooms == [] %>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Listing classrooms</h1>

<p id="notice"><%= notice %></p>

<table id="classrooms">
  <thead>
    <tr>
      <th id="name_header"><%=link_to 'Name', classrooms_path(:sort => 'name')%></th>
      <th id="occupancy_header"><%=link_to 'Max occupancy', classrooms_path(:sort => 'occupancy')%></th>  
      <th>Details</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.name %></td>
        <td><%= classroom.max_occupancy %></td>
        <td><%= classroom.details %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Delete', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classroom.name %>
</p>

<p>
  <strong>Max occupancy:</strong>
  <%= @classroom.max_occupancy %>
</p>

<p>
  <strong>Details:</strong>
  <%= @classroom.details %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>