config/routes.rb
Rails.application.routes.draw do
  resources :lessons

  resources :classrooms

  root 'lessons#index'

  get 'classroom/available' => 'classrooms#available'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	extend SimpleCalendar
	has_calendar

	#form validation
  validates :ends_at, :starts_at, :title, :instructor, :location, presence: true
	validate :some_grade_level_selected
	validate :ends_at_after_starts_at
	validate :enrollment_not_negative
  	validate :lesson_max_more_than_classroom_capacity
  	validate :end_date_after_start_date



	def lesson_max_more_than_classroom_capacity
	  classroom = Classroom.find_by(name: location)
	  if classroom == nil || max_enrollment == nil
	  elsif max_enrollment > classroom.max_occupancy
	    errors.add(:max_enrollment, "for this classroom cannot exceed #{classroom.max_occupancy}")
	  end
	end

  def starts_date_not_nil
    if start_date == nil
      errors.add(:start_date, "can't be empty")
    end
  end
	def end_date_after_start_date
		if mon==true || tue==true || wed==true || thu==true || fri==true
			if end_date < start_date
				errors.add(:until, "can't be before start date for repeating lessons")
			end
		end
	end


	def ends_at_after_starts_at
		if ends_at.to_i < starts_at.to_i
			errors.add(:ends_at, "can't be before starts time")
		end
	end

	def some_grade_level_selected
		if g1_3 == false && g3_5 == false && g6_8 == false
			errors.add(:grade_levels, "must be selected")
		end
	end

	def enrollment_not_negative
		if max_enrollment == nil || max_enrollment < 1
			errors.add(:max_enrollment, "must be a positive value")
		end
	end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    @lessons13 = Lesson.where(g1_3: true)
    @lessons35 = Lesson.where(g3_5: true)
    @lessons68 = Lesson.where(g6_8: true)

    #find date span to display on calendar
    @start_date = params[:start_date] || session[:start_date] || {}
    if @start_date == {}
      @start_date = Date.today
    end

    if params[:start_date] != session[:start_date]
      session[:start_date] = @start_date
      redirect_to :start_date => @start_date and return
    end

  end

  # GET /lessons/1
  # GET /lessons/1.json
  #def show
  #end

  # GET /lessons/new
  def new
    @lesson = Lesson.new

    #generate list of classrooms to select from for location
    @classrooms = Classroom.all
    @roomsList = [[]]
    @colorsList = [[]]
    @classrooms.each do |classroom|
      @roomsList << [classroom.name]
      @colorsList << [classroom.color]
    end
    @classroomSelect = @roomsList
    @classroomsColorSelect = @colorsList

    #If we're passed a date, store it
    if params[:date] != nil
      #sending date through params turns it into a string, convert back
      @selected_date = Date.parse params[:date]
    end
    @selected_room = params[:room].to_s
  end

  # GET /lessons/1/edit
  def edit
    #generate list of   classrooms to select from for location
    @lesson = Lesson.find(params[:id])
    @classrooms = Classroom.all
    @roomsList = [[]]
    @colorsList = [[]]
    @classrooms.each do |classroom|
      @roomsList << [classroom.name]
      @colorsList << [classroom.color]
    end
    @classroomSelect = @roomsList
    @classroomsColorSelect = @colorsList
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    #generate list of classrooms to select from for location
    @classrooms = Classroom.all
    @roomsList = [[]]
    @colorsList = [[]]
    @classrooms.each do |classroom|
      @roomsList << [classroom.name]
      @colorsList << [classroom.color]
    end
    @classroomSelect = @roomsList
    @classroomsColorSelect = @colorsList


    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    #generate list of classrooms to select from for location
    @classrooms = Classroom.all
    @roomsList = [[]]
    @colorsList = [[]]
    @classrooms.each do |classroom|
      @roomsList << [classroom.name]
      @colorsList << [classroom.color]
    end
    @classroomSelect = @roomsList
    @classroomsColorSelect = @colorsList


    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :instructor, :starts_at, :ends_at, :location, :max_enrollment, :description, :g1_3, :g3_5, :g6_8, :mon, :tue, :wed, :thu, :fri, :end_date, :color, :start_date)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper

	#find lessons occuring on a given day
	def lessonsOn(date, lessons, grade_level)
		dayTomorrow = (date + 1)
		dayYesterday = (date - 1)
    classes = lessons.where("\"lessons\".\"start_date\" < ?", dayTomorrow)
    classes = classes.where("\"lessons\".\"end_date\" > ?" , dayYesterday)

		days_of_week = ["sun","mon", "tue", "wed", "thu", "fri","sat"]
		dayOfWeek = days_of_week[(date.wday)]
		if dayOfWeek == "sun" || dayOfWeek == "sat"
			#classes don't reccur on weekends
			return classes.where(start_date: date.beginning_of_day..date.end_of_day).order(:starts_at)
		else
			dayStart = "#{date.strftime("%Y-%m-%d")} 05:00:00.000000"
			dayTomorrow = date + 1
			dayEnd = "#{dayTomorrow.strftime("%Y-%m-%d")} 04:59:59.999999"
			#SQL to return lessons for the appropriate grade level that occur on a given day
      classes = lessons.where("\"lessons\".\"start_date\" < ? or \"lessons\".\"start_date\" = ?", dayTomorrow, date)
      classes = classes.where("\"lessons\".\"end_date\" > ?" , dayYesterday)
			classes = classes.where("\"lessons\".\"#{dayOfWeek}\" = \'t\'")
		  return classes.where("\"lessons\".\"#{grade_level}\" = \'t\'").order(:starts_at)
  end
	end
    def dailyAvailableClassrooms(date)

      days_of_week = ["sun","mon", "tue", "wed", "thu", "fri","sat"]
      dayOfWeek = days_of_week[(date.wday)]
      availables = []
      if dayOfWeek != "sun" && dayOfWeek != "sat"
	      allRooms = Classroom.all.order(:name)
	      allRooms.each do |classroom|
	        if classNotOccupiedOnDay(classroom, date)
	          availables << classroom
	        end
	      end
	  end
	  return availables
    end

    def classNotOccupiedOnDay(classroom, date)
      days_of_week = ["sun","mon", "tue", "wed", "thu", "fri","sat"]
      dayOfWeek = days_of_week[(date.wday)]
      #currently only returns classes available on a specific day
			classrooms = Lesson.where("\"lessons\".\"start_date\" = ? or \"lessons\".\"start_date\" < ?", date, date + 1)
      classrooms = classrooms.where("\"lessons\".\"#{dayOfWeek}\" = \'t\'")
      classrooms = classrooms.where("\"lessons\".\"end_date\" > \'#{date-1}\'")
      @lessons = classrooms.where("\"lessons\".\"location\" = ?", classroom.name)
      if @lessons == []
        return true
      else
        return false
      end
    end

	def getLessonColor(lesson)
		lessons_classroom = Classroom.where(name: lesson.location)
		if lessons_classroom.empty?
			"black"
		else
			lessons_classroom[0].color
		end
	end

end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prevented this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div>
    <%= f.label :title %>
    </div>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <div>
    <%= f.label :instructor %>
    </div>
    <%= f.text_field :instructor %>
  </div>
  <div class="field">
    <div>
    <%= f.label :grade_levels %>
    </div>
    1-3
    <%= f.check_box :g1_3 %>
    3-5
    <%= f.check_box :g3_5 %>
    6-8
    <%= f.check_box :g6_8 %>
  </div>
  <div class="field">
    <div>
    <%= f.label :starts_at %>
    </div>
    &nbsp Date
    <%= f.date_select :start_date, selected: @selected_date if params[:date]!=nil %>
    <%= f.date_select :start_date if params[:date]==nil %>
    <br>
    &nbsp Time
    <%= f.time_select :starts_at, :ignore_date => true, prompt: true, ampm: true %>
  </div>
  <div class="field">
    <div>
    <%= f.label :ends_at %>
    </div>
    &nbsp Time
    <%= f.time_select :ends_at, :ignore_date => true, prompt: true, ampm: true %>
  </div>
  <div class="field">
    <div>
    <%= f.label 'Repeat every' %>
    </div>
    &nbsp Monday
    <%= f.check_box :mon %>|
    Tuesday
    <%= f.check_box :tue %>|
    Wednesday
    <%= f.check_box :wed %>|
    Thursday
    <%= f.check_box :thu %>|
    Friday
    <%= f.check_box :fri %>
    <br> &nbsp <%=f.label :until %>
    <%= f.date_select :end_date, selected: @selected_date if params[:date]!=nil %>
    <%= f.date_select :end_date if params[:date]==nil %>
  </div>
  <div class="field">
    <div>
    <%= f.label :location %>
    </div>
    <%= f.select :location, @classroomSelect, selected: @selected_room if params[:room]!=nil%> 
    <%= f.select :location, @classroomSelect if params[:room]==nil%> 
    <!--<%= link_to "See Available Classrooms", classroom_available_path %>-->
  </div>
  <div class="field">
    <div>
    <%= f.label :max_enrollment %>
    </div>
    <%= f.number_field :max_enrollment, min: 0 %>
  </div>
  <div class="field">
    <div>
    <%= f.label :description %>
    </div>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/_tri_cal.html.erb
<%= link_to 'View Current Week', 
    	lessons_path(:start_date => Date.today) %>

<table>
  
  <tr id='1-3row'>
    <th class='grades'>
      <strong>Grades<br>1-3</strong>
    </th>
    <th>
      <div class= "weekCalendar" id='calendar13'>    
        <%= week_calendar do |date| %>
          <div class= 'calendarDate'>
            <strong><%= link_to date.day, controller: "lessons", action: "new", date: date %></strong>
          </div>
          <% lessonsOn(date, @lessons13, "g1_3").each do |lesson| %>
            <div class='lessonBlock'>
              <strong><%= link_to lesson.title, lesson, style: "color: #{getLessonColor(lesson)}" %></strong><br>
              <%= lesson.starts_at.strftime("%I:%M") %>-<%= lesson.ends_at.strftime("%I:%M") %><br>
              <%= lesson.instructor %>
            </div>
          <% end %>
        <% end %>
      </div>
    </th>
  </tr>

  <tr id='3-5row'>
    <th class='grades'>
      <strong>Grades<br>3-5</strong>
    </th>
    <th>
      <div class= "weekCalendar" id='calendar35'>
      <%= week_calendar title: '', previous_link: '', next_link: '' do |date| %>
        <div class= 'calendarDate'>
          <strong><%= link_to date.day, controller: "lessons", action: "new", date: date %></strong>
        </div>
        <% lessonsOn(date, @lessons35, "g3_5").each do |lesson| %>
          <div class='lessonBlock'>
              <strong><%= link_to lesson.title, lesson, style: "color: #{getLessonColor(lesson)}" %></strong><br>
              <%= lesson.starts_at.strftime("%I:%M") %>-<%= lesson.ends_at.strftime("%I:%M") %><br>
            <%= lesson.instructor %>
          </div>
        <% end %>
      <% end %>
      </div>
    </th>
  </tr>

  <tr id='6-8row'>
    <th class='grades'>
      <strong>Grades<br>6-8</strong>
    </th>
    <th>
      <div class= "weekCalendar" id='calendar68'>
        <%= week_calendar title: '', previous_link: '', next_link: '' do |date| %>
          <div class= 'calendarDate'>
            <strong><%= link_to date.day, controller: "lessons", action: "new", date: date %></strong>
          </div>

          <% lessonsOn(date, @lessons68, "g6_8").each do |lesson| %>
            <div class='lessonBlock'>
              <strong><%= link_to lesson.title, lesson, style: "color: #{getLessonColor(lesson)}" %></strong><br>
              <%= lesson.starts_at.strftime("%I:%M") %>-<%= lesson.ends_at.strftime("%I:%M") %><br>
              <%= lesson.instructor %>
            </div>
          <% end %>
        <% end %>
      </div>
    </th>
  </tr>

  <tr id=''>
    <th class='grades'>
      <strong>Available<br>Classrooms</strong>
    </th>
    <th>
      <div class= "weekCalendarClassrooms" id='classrooms'>
        <%= week_calendar title: '', previous_link: '', next_link: '' do |date| %>
          <div class= 'calendarDate'>
            <strong><%= date.day %></strong>
          </div>

          <% dailyAvailableClassrooms(date).each do |classroom| %>
            <div class='classroom'>
              <%= link_to classroom.name, new_lesson_path(date: date, room: classroom.name), style: "color: #{classroom.color}" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </th>
  </tr>

</table>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<h1>Calendar</h1>

<p id="notice"><%= notice %></p>

<%= link_to 'New Lesson', new_lesson_path %>
<br></br>

<%= render 'tri_cal' %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @lesson.instructor %>
</p>

<p>
  <strong>Grade Levels:</strong>
  <%= "1-3" if @lesson.g1_3 == true %>
  <%= "3-5" if @lesson.g3_5 == true %>
  <%= "6-8" if @lesson.g6_8 == true %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @lesson.starts_at.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @lesson.ends_at.strftime("%I:%M %p") %>
</p>

<p>
  <strong><%= "From:" if @lesson.mon == true || @lesson.tue == true || @lesson.wed == true || @lesson.thu == true || @lesson.fri == true %></strong>
  <strong><%= "Date:" if @lesson.mon == false && @lesson.tue == false && @lesson.wed == false && @lesson.thu == false && @lesson.fri == false %></strong>
  <%= @lesson.start_date %>

  <strong><%= "to" if @lesson.mon == true || @lesson.tue == true || @lesson.wed == true || @lesson.thu == true || @lesson.fri == true %> </strong>
  <%= @lesson.end_date if @lesson.mon == true || @lesson.tue == true || @lesson.wed == true || @lesson.thu == true || @lesson.fri == true %>
</p>
<p>
</p>

<p>
  <strong><%= "Repeats every:" if @lesson.mon == true || @lesson.tue == true || @lesson.wed == true || @lesson.thu == true || @lesson.fri == true %></strong>
  <%= "Monday" if @lesson.mon == true %>
  <%= "Tuesday" if @lesson.tue == true %>
  <%= "Wednesday" if @lesson.wed == true %>
  <%= "Thursday" if @lesson.thu == true %>
  <%= "Friday" if @lesson.fri == true %>
</p>

<p>
  <strong>Location:</strong>
  <%= @lesson.location %>
</p>

<p>
  <strong>Max enrollment:</strong>
  <%= @lesson.max_enrollment %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Delete', @lesson, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', lessons_path %>